apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "climate-warehouse.fullname" . }}-config
  labels:
    {{- include "climate-warehouse.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi