apiVersion: v1
kind: Service
metadata:
  name: {{ include "climate-warehouse.fullname" . }}
  labels:
    {{- include "climate-warehouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "climate-warehouse.selectorLabels" . | nindent 4 }}
